[id='assembly-kogito-developing-decision-services_{context}']
:KOGITO-ENT:

ifdef::KOGITO-ENT[]
include::_artifacts/document-attributes.adoc[]
endif::[]

= Developing decision services with {PRODUCT}
:context: kogito-developing-decision-services
ifdef::KOGITO-ENT[]
:doctype: book
:imagesdir: _images
include::_artifacts/author-group.adoc[]
endif::[]

// Purpose statement for the assembly
As a developer of business decisions, you can use {PRODUCT} business automation to develop decision services using Decision Model and Notation (DMN) models, Drools Rule Language (DRL) rules, XLS or XLSX spreadsheet decision tables, or a combination of all three methods.

ifdef::KOGITO-ENT[]
[IMPORTANT]
====
{PRODUCT} is currently available for Development Preview. Development Preview releases contain features and APIs that might not be fully tested and that might change in the final GA version. Users are discouraged from using Development Preview software in production or for business-critical workloads.  Because this is not production-ready software, users are not able to open support tickets. To learn more about {PRODUCT}, please contact your Red Hat representative or send an email to Kogito-earlyaccess@redhat.com. Red Hat will address reported issues at its own discretion.
====
endif::[]

// Modules - concepts, procedures, refs, etc.

include::modules/decision-services/ref-decision-authoring-assets.adoc[leveloffset=+1]
include::modules/creating-running/ref-kogito-app-examples.adoc[leveloffset=+1]

include::assembly-kogito-using-dmn.adoc[]
include::assembly-kogito-using-drl.adoc[]
include::assembly-kogito-using-spreadsheet-decision-tables.adoc[]
include::assembly-kogito-decision-engine.adoc[]

ifdef::KOGITO-ENT[]
== Additional resources
* {URL_CREATING_RUNNING}[_{CREATING_RUNNING}_]
* {URL_DEPLOYING_ON_OPENSHIFT}[_{DEPLOYING_ON_OPENSHIFT}_]
* {URL_PROCESS_SERVICES}[_{PROCESS_SERVICES}_]
* {URL_CONFIGURING_KOGITO}[_{CONFIGURING_KOGITO}_]

// Versioning info
include::_artifacts/versioning-information.adoc[]
endif::[]
