[id='kie-server-java-clients-ref_{context}']
= Supported {KIE_SERVER} Java clients

The following are some of the Java client services available in the `org.kie.server.client` package of your {PRODUCT} distribution. You can use these services to interact with related resources in {KIE_SERVER} similarly to the {KIE_SERVER} REST API.

* `KieServicesClient`: Used as the entry point for other {KIE_SERVER} Java clients, and used to interact with KIE containers
* `JobServicesClient`: Used to schedule, cancel, re-queue, and get job requests
* `ProcessServicesClient`: Used to start, signal, and abort processes or work items
* `QueryServicesClient`: Used to query processes, process nodes, and process variables
* `RuleServicesClient`: Used to send commands to the server to perform rule-related operations (for example, insert objects into the working memory or execute rules)
* `SolverServicesClient`: Used to perform all {PLANNER} operations, such as getting the solver state and the best solution, or disposing of a solver
* `UserTaskServicesClient`: Used to perform all user-task operations (such as to start, claim, or cancel a task) and query tasks by specified field (such as process instances ID or user)
* `UIServicesClient`: Used to get String representation of forms (XML or JSON) and of the process image (SVG)
* `ProcessAdminServicesClient`: Provides an interface for operations with process instances (found in `~/org/kie/server/client/admin`)
* `UserTaskAdminServicesClient`: Provides an interface for operations with user tasks (found in `~/org/kie/server/client/admin`)

The `getServicesClient` method provides access to any of these clients:

[source,java]
----
RuleServicesClient rulesClient = kieServicesClient.getServicesClient(RuleServicesClient.class);
----

For the full list of available {KIE_SERVER} Java clients, download the *{PRODUCT} {PRODUCT_VERSION_LONG} Source Distribution* from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Red Hat Customer Portal] and navigate to `~/{PRODUCT_FILE}-sources/src/droolsjbpm-integration-$VERSION/kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client`.
