// To reuse this module, ifeval the title to be more specific as needed.

[id='knowledge-store-rest-api-jobs-ref_{context}']
= Jobs (API requests)

All `POST` and `DELETE` requests in the Knowledge Store REST API return a job ID associated with each request, in addition to the returned request details. You can use a job ID to view the request status or delete a sent request.

Knowledge Store REST API requests, or _jobs_, can have the following statuses:

.Job statuses
[cols="1,3a", frame="all", options="header"]
|===
|Status
|Description

|`ACCEPTED`
|The job was accepted and is being processed.

|`BAD_REQUEST`
|The request was not accepted as it contained incorrect content.

|`RESOURCE_NOT_EXIST`
|The requested resource (path) does not exist.

|`DUPLICATE_RESOURCE`
|The resource already exists.

|`SERVER_ERROR`
|An error on the server side occurred.

|`SUCCESS`
|The job finished successfully.

|`FAIL`
|The job failed.

|`APPROVED`
|The job was approved.

|`DENIED`
|The job was denied.

|`GONE`
|The job ID could not be found. A job can be `GONE` in the following cases:

* The job was explicitly removed.
* The job finished and has been deleted from a status cache. A job is removed from a status cache after the cache has reached its maximum capacity.
* The job never existed.
|===

The Knowledge Store REST API supports the following endpoints for retrieving or deleting sent API requests. The Knowledge Store REST API base URL is `\http://SERVER:PORT/{URL_COMPONENT_CENTRAL}/rest/`. All requests require basic HTTP Authentication or token-based authentication for the `rest-all` user role.

[GET] /jobs/{jobId}::
+
--
Returns the status of a specified job (a previously sent API request)

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`jobId`
|ID of the job to be retrieved (example: `1541010216919-1`)
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "status": "SUCCESS",
  "jobId": "1541010216919-1",
  "result": null,
  "lastModified": 1541010218352,
  "detailedResult": [
    "level:INFO, path:null, text:Build of module 'Mortgage_Process' (requested by system) completed.\n Build: SUCCESSFUL"
  ]
}
----
--
[DELETE] /jobs/{jobId}::
+
--
Deletes a specified job (a previously sent API request). If the job is not being processed yet, this request removes the job from the job queue. This request does not cancel or stop an ongoing job.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`jobId`
|ID of the job to be deleted (example: `1541010216919-1`)
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "status": "GONE",
  "jobId": "1541010216919-1",
  "result": null,
  "lastModified": 1541132054916,
  "detailedResult": [
    "level:INFO, path:null, text:Build of module 'Mortgage_Process' (requested by system) completed.\n Build: SUCCESSFUL"
  ]
}
----
--
